name: member_app_template
description: Company template app based on Clean Architecture + Riverpod.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_riverpod: ^2.5.1
  image_picker: ^1.1.2
  freezed_annotation: ^2.4.4
  go_router: ^14.2.0
  dio: ^5.7.0
  encrypt: ^5.0.3
  json_annotation: ^4.9.0
  meta: ^1.12.0
  core_network:
    path: ../mobile_core_sdk/packages/core_network
  core_foundation:
    path: ../mobile_core_sdk/packages/core_foundation
  core_storage:
    path: ../mobile_core_sdk/packages/core_storage
  core_tool_kit:
    path: ../mobile_core_sdk/packages/core_tool_kit
  core_ui_kit:
    path: ../mobile_core_sdk/packages/core_ui_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.25.8
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  generate: true
  uses-material-design: true
