name: core_tool_kit
description: Shared tooling utilities including file-based app logging.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.1'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
